### ISSUE TITLE
Make another example with plugo child that doesn't return anything

### ISSUE THREAD

**Issue by marcelloh** [curzodo/plugo#4]
I've tried to add an extra function inside the child example:
Removed the Add part and added:
```
	p.Expose("justHello", justHello)
```
then at the end added:
```
func justHello() {
	log.Println(`main.go:48 hello`)
}
```

In the parent:
commented out the add parts and added:
```
	_, _ = p.CallWithTimeout("Child", "justHello", 1000)
```
It doesn't print anything from the child :-(
So I must be confused how to use it.

Where I put everything back as it was, and put just that println inside the add function, I didn't see that either.

**Comment by curzodo** [comment]
I think the problem is that the child process is not connected to any terminal, so the code inside justHello() runs, but there is nowhere to print to. A solution would be to implement a logging function on the parent, expose that function, and then when you want to log something you could do `p.CallWithTimeout("Parent", "Println", 1000, "Test input"` on the child.

The child is executed with cmd/exec, so I have connected the stdout of the child to the stdout of the parent and released the update. Your code should work as expected now, as long as log writes to stdout.

**Comment by marcelloh** [comment]
Yes, that did the trick :-)
For "basic" debugging we at least need some output from within the child
